import fs from 'fs';
import path from 'path';

export function createPlaceholdersForPack(pack: any, missingRefs: string[]) {
  const created: string[] = [];
  pack.features = pack.features || [];

  for (const m of missingRefs) {
    if (!m.startsWith('feature:')) continue;
    const exists = (pack.features || []).find((f: any) => f.externalId === m);
    if (exists) continue;
    const name = m.replace(/^feature:/, '').replace(/[_:]/g, ' ');
    const placeholder = { externalId: m, name: name, description: 'Placeholder generated by importer --update' };
    pack.features.push(placeholder);
    created.push(m);
  }

  return { pack, createdPlaceholders: created };
}

export function writePackBackup(filePath: string, pack: any) {
  const backupPath = `${filePath}.bak.${Date.now()}`;
  fs.copyFileSync(filePath, backupPath);
  fs.writeFileSync(filePath, `${JSON.stringify(pack, null, 2)}\n`, 'utf-8');
  return { backupPath, filePath };
}

export default { createPlaceholdersForPack, writePackBackup };
