ALTER TABLE "monster_templates"
  ADD COLUMN "size" TEXT,
  ADD COLUMN "creature_type" TEXT,
  ADD COLUMN "alignment" TEXT,
  ADD COLUMN "hit_dice" TEXT,
  ADD COLUMN "speed" TEXT,
  ADD COLUMN "strength" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "dexterity" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "constitution" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "intelligence" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "wisdom" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "charisma" INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN "damage_immunities" TEXT,
  ADD COLUMN "condition_immunities" TEXT,
  ADD COLUMN "senses" TEXT,
  ADD COLUMN "languages" TEXT,
  ADD COLUMN "traits" TEXT,
  ADD COLUMN "actions" TEXT,
  ADD COLUMN "legendary_actions" TEXT;